name: Terratest

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  terratest:
    name: Terratest
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Set up Golang 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Download Go Modules
        working-directory: deploy/test
        run: go mod download

      - name: Run Go Tests
        working-directory: deploy/test
        run: go test -v
        env:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}