name: Terratest

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  go-tests:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Download Go Modules
        working-directory: deploy/test
        run: go mod download

      - name: Run Go Tests
        working-directory: deploy/test
        run: go test -v